### ISSUE TITLE
COSMIC Terminal MVP Issue List

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-term#101]
- [x] https://github.com/pop-os/cosmic-term/issues/89
- [x] https://github.com/pop-os/cosmic-term/issues/90
- [x] https://github.com/pop-os/cosmic-term/issues/92
- [ ] https://github.com/pop-os/cosmic-term/issues/93
- [x] https://github.com/pop-os/cosmic-term/issues/86
- [x] https://github.com/pop-os/cosmic-term/issues/91
- [ ] https://github.com/pop-os/cosmic-term/issues/94
- [x] https://github.com/pop-os/cosmic-term/issues/96
- [x] https://github.com/pop-os/cosmic-term/issues/98
- [x] https://github.com/pop-os/cosmic-term/issues/99
- [x] https://github.com/pop-os/cosmic-term/issues/100
- [x] https://github.com/pop-os/cosmic-term/issues/102
- [x] https://github.com/pop-os/cosmic-term/issues/103
- [ ] https://github.com/pop-os/cosmic-term/issues/154

**Comment by Piroro-hs** [comment]
Does #102 resolved correctly?
Background color used for COSMIC Light is currently black, which makes the theme almost unreadable.

**Comment by jackpot51** [comment]
@Piroro-hs you should comment on that issue instead. You should be switching the app theme to Light if you want to use COSMIC Light.

**Comment by WatchMkr** [comment]
Removed Change Splits to match COSMIC UX https://github.com/pop-os/cosmic-term/issues/97

**Comment by WatchMkr** [comment]
Closing. Using milestones.

**Comment by FMorschel** [comment]
I'm guessing this can be unpinned now, too.
