### ISSUE TITLE
Arrow keys not working in `less`

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-term#13]
Not sure why, given it works in bash and nvim, `sys.stdin.readline()` in python shows the exact same bytes for arrow keys as xterm, and the `TERM` value isn't the issue.

hjkl however works fine.

**Comment by MoSal** [comment]
To test this, add a `dbg!` at the start of the `Up` case:

* In zsh, type a partial command in zsh, and hit the `Up` key. `APP_CURSOR` mode should be `true`. Testing with `less` also works.
* Run `cat` without arguments, then hit the `Up` key. In this case, `APP_CURSOR` is `false`, and you can see that the sequence passed is not the `APP_CURSOR` one.
