### ISSUE TITLE
Removing profile leaves the action icons floating in the sidebar

### ISSUE THREAD

**Issue by pszpetkowski** [pop-os/cosmic-term#143]
Hello,

This is a simple cosmetic issue that happens if you remove a profile. Happens for the latest master (`1b0d018`) I've compiled from AUR.

**Configuration**:

- GNOME 45
- Mesa 24.0.1
- Wayland

**Screencast**:

[Screencast from 2024-02-23 03-32-23.webm](https://github.com/pop-os/cosmic-term/assets/18597734/bd7b6014-de83-45df-b5da-833668fcab34)

**Comment by WatchMkr** [comment]
This appears to be fixed.
