### ISSUE TITLE
Newly opened terminal has two tabs, one is unresponsive

### ISSUE THREAD

**Issue by flukejones** [pop-os/cosmic-term#146]
Newly opened terminal has two tabs, the first one is unresponsive until clicked. What it looks like is that the process of that tab is not drawing unless it receives a mouse-button input.

**Comment by leviport** [comment]
I believe this is a duplicate of https://github.com/pop-os/cosmic-term/issues/36 (and probably related to https://github.com/pop-os/cosmic-term/issues/50). I'll close this and reopen #36
