### ISSUE TITLE
Broken rendering in btm 

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/cosmic-term#166]
`bottom` is a `top` alternative written in rust.

It is the only terminal application that I frequently use and is broken in cosmic-term. Everything else works perfectly fine.

Here is a screenshot. I'm not sure what is causing the TUI to break apart over time.

 
![screenshot-2024-03-22-04-30-18](https://github.com/pop-os/cosmic-term/assets/2222199/3319b252-d222-455c-9e0a-0d2f8285f953)

**Comment by jackpot51** [comment]
The braille font used here is not being modified to the correct width, this is a problem with cosmic-text: https://github.com/pop-os/cosmic-text/issues/237

**Comment by snaggen** [comment]
I assume you don't have a mono space brail font installed, so it fallbacks to a non-mono brail font.  Installing Iosevka font will most likely make things look correct again. 
See issue https://github.com/pop-os/cosmic-term/issues/66 for reference. 

How does it look on your system in other terminals? Are they forcing the font to be mono?

**Comment by leviport** [comment]
Closing to track in https://github.com/pop-os/cosmic-text/issues/237
