### ISSUE TITLE
[Profiles] Profile tabs with command line close immediately

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-term#179]
When a profile has a command line option (e.g. neofetch, lsblk), the tab using that profile is immediately closed.
If that profile is the default profile, the terminal closes immediately after launching.

**Comment by leb-kuchen** [comment]
You may find this alacritty github issue helpful: https://github.com/alacritty/alacritty/issues/1672
For fish and nu you have use the init-command and execute flags respectively if you do not want to exit the shell. For other shells I do not know.

**Comment by git-f0x** [comment]
This is with default bash in Pop!_OS.
If this is an issue in alacritty, and cannot be fixed in cosmic-term, then the command line option should probably be removed until it is fixed upstream, since it's not exactly expected behavior that using this option would just close the tab.

**Comment by mmstick** [comment]
cosmic-term does not use the alacritty binary, so what applies there does not apply here. In general, a terminal will naturally exit once the profile's command has exited.

**Comment by git-f0x** [comment]
So is this intended behavior? I assumed that Profiles are used more for aesthetic reasons (e.g. neofetch on launch, customized tab names) or to run something (script, etc.) and continue using the terminal.

**Comment by leb-kuchen** [comment]
Shell options are provided by the alacritty_terminal crate, so the linked  issue is very relatable. 
https://docs.rs/alacritty_terminal/0.23.0/alacritty_terminal/tty/struct.Shell.html

**Comment by leb-kuchen** [comment]
I use them to set a default shell and I do not want to run `chsh -s`, cause I am a little scared of running exotic shells in a tty.

**Comment by leb-kuchen** [comment]
alacritty_terminal provides a hold option, so it could be implemented quiet easily. I do not know if it should be default, the advantage is that you still have access to rest of the GUI.
