### ISSUE TITLE
Cosmic Terminal freezes when running the exit command

### ISSUE THREAD

**Issue by VPeti1** [pop-os/cosmic-term#191]
If i type in the 'exit' command into Cosmic Terminal that tab just freezes. This also happens if i pkill the shell.

**Comment by ChocolateLoverRaj** [comment]
When I type `exit` it exits without freezing.

**Comment by leviport** [comment]
Same for me running Pop with COSMIC DE. 

@VPeti1 can you share some details about which OS and DE you're running when this happens?

**Comment by VPeti1** [comment]
Im using Arch linux with the Cosmic DE. I had built Cosmic Terminal from source using just

**Comment by VPeti1** [comment]
![image](https://github.com/pop-os/cosmic-term/assets/157271500/2dccd34a-7c19-40ad-b6ce-49c5527d452b)
It just hangs like that. I am using the fish shell maybe that's the problem

**Comment by ChocolateLoverRaj** [comment]
I'm on NixOS. I tried it with the package from nixos unstable and also running `cargo r` from source. I'm using bash.

**Comment by MoSal** [comment]
@VPeti1 

What happens if you run:

1. `kill $fish_pid`
2. `kill -9 $fish_pid`
3. `kill $(ps -o ppid= -p $fish_pid)`

**Comment by VPeti1** [comment]
@MoSal It freezes the terminal aswell

**Comment by MoSal** [comment]
@VPeti1
All three commands? even the third one?

If yes, what happens if you run:
```
kill -9 $(ps -o ppid= -p $fish_pid)
```

**Comment by VPeti1** [comment]
@MoSal Then it closes Cosmic terminal but the other ones just freeze the terminal

**Comment by surrealreverie** [comment]
Not sure if this is relevant, but for each profile there is an option called "Hold" which prevents the terminal from closing even if the child process is terminated.

![hold option](https://github.com/pop-os/cosmic-term/assets/55920099/70dbe78e-3158-4ce7-9f96-6c378527bb61)

If you have set a default profile, or opened a new tab with a profile, try disabling this option on that profile, and then try exiting.

**Comment by leviport** [comment]
I think this is fixed now. This can be reopened if I'm mistaken.
