### ISSUE TITLE
[Feature request] Intelligent Ctrl+C

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [pop-os/cosmic-term#192]
[Tabby](https://tabby.sh/) has this feature, but Tabby's kind of slow. It would be great of this super fast terminal also had this feature. The feature: If you have text selected and do Ctrl+C, the selection will get copied to the clipboard, and the command will not get stopped. If no text is selected, then Ctrl+C will stop the command.

Same GNOME feature request: https://gitlab.gnome.org/GNOME/console/-/issues/99
Same KDE feature request: https://invent.kde.org/utilities/konsole/-/merge_requests/520#note_342397

I can try adding this feature since this is written in Rust and I like Rust, but I haven't looked at the code so I'm not sure how hard it'll be for me.

**Comment by demostanis** [comment]
What about Ctrl-V tho? I use it all the time to insert raw characters.

**Comment by ChocolateLoverRaj** [comment]
> What about Ctrl-V tho? I use it all the time to insert raw characters.

My PR #195 doesn't change the behavior of any paste commands. I personally would change the paste shortcut to Ctrl+V, but you can leave it as Ctrl+Shift+V.
