### ISSUE TITLE
Rename default branch to main?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [pop-os/cosmic-term#193]
Maybe consider changing the default branch from `master` to `main`.

More info: 
- https://thenextweb.com/news/github-plans-to-replace-racially-insensitive-terms-like-master-and-whitelist
- https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

**Comment by jackpot51** [comment]
Our build system currently uses the `master` branches as a way to stage releases and we're not in a good spot to transition. There is a PR for that here: https://github.com/pop-os/pop/pull/2075
