### ISSUE TITLE
Enter does nothing on shells other than bash.

### ISSUE THREAD

**Issue by leb-kuchen** [pop-os/cosmic-term#2]
ERROR wgpu_hal::vulkan::adapter] get_physical_device_surface_present_modes: An unknown error has occurred, due to an implementation or application bug
I have so far tried pwsh and nu.

**Comment by MoSal** [comment]
And `BackSpace` does nothing in ZSH ;)

**Comment by jackpot51** [comment]
@MoSal should be fixed in d7798f7

**Comment by jackpot51** [comment]
@leb-kuchen please try again

**Comment by leb-kuchen** [comment]
works
