### ISSUE TITLE
Clipboard broken on Hyprland

### ISSUE THREAD

**Issue by Aqa-Ib** [pop-os/cosmic-term#201]
[Hyprland's new Wayland implementation](https://github.com/hyprwm/Hyprland/pull/5999) broke the clipboard of cosmic-term. It is no longer possible to copy nor paste.

Neovim executed inside of cosmic-term synchronizes with the system clipboard, but for it to work I have to use its internal keybindings 'y' and 'p'.

Other terminal emulators that have a working clipboard on Hyprland: Kitty, Contour, Konsole, Gnome-terminal.

Would someone be so kind to help fixing this ? 

Thanks for your attention.

**Comment by jackpot51** [comment]
You indicate that a hyprland change broke the clipboard and I don't know of other environments where it is broken so I don't think this is a cosmic-term issue.

**Comment by Aqa-Ib** [comment]
Well, Hyprland's developer thinks that, because every other client work, the bug is somewhere in this chain: (alacritty -> some cb lib -> smithay_cb -> smithay_client).

Who knows...

**Comment by sungyoonc** [comment]
Could be related https://github.com/hyprwm/Hyprland/issues/6069

**Comment by MoSal** [comment]
> Well, Hyprland's developer thinks that, because every other client work, the bug is somewhere in this chain: "alacritty -> some cb lib -> smithay_cb -> smithay_client".
> 
> Who knows...

The first two in that chain don't apply here.
Hope that helps.

**Comment by vaxerski** [comment]
smithay_cb binds the wl_seat global again, causing the terminal to have two bound wl_seats, which is cursed and should never be done. The reason it broke is I assume no app binds wl_seat twice, and thus only send events to the first.

**Comment by MoSal** [comment]
> smithay_cb binds the wl_seat global again, causing the terminal to have two bound wl_seats,

Maybe I'm reading it wrong, but this looks like it was a deliberate design decision made with the smithayclipboard v0.5 release:
https://github.com/Smithay/smithay-clipboard/commit/bb652c775b8226e55a22437476bcf45bffb5ed6c

> which is cursed and should never be done. The reason it broke is I assume no app binds wl_seat twice, and thus only send events to the first.

Maybe it is cursed and should never be done. Regardless, your assumption proved to be wrong.
