### ISSUE TITLE
[Bug] Lines that start with a character of an RTL language should be aligned to the right of the screen

### ISSUE THREAD

**Issue by shadyalfred** [pop-os/cosmic-term#221]
![Screenshot_7](https://github.com/pop-os/cosmic-term/assets/3685582/1361aacf-dd96-485c-b0cb-d28acf6443fc)
Version tested on:
![Screenshot_8](https://github.com/pop-os/cosmic-term/assets/3685582/ef15540e-b7f9-4628-bf0d-f5d075dc2a2c)

Correct rendering with a term emulator running in Emacs with global bidi mode:
![Screenshot_5](https://github.com/pop-os/cosmic-term/assets/3685582/f86f4516-dbd8-49ff-bf80-609fe5a711c5)

**Comment by MoSal** [comment]
This is deliberate for now.
Ability to force RTL or auto-dir will be added.
