### ISSUE TITLE
Terminal loses focus when clicking title bar

### ISSUE THREAD

**Issue by tbillington** [pop-os/cosmic-term#229]
After clicking the title bar, or more commonly when moving cosmic-term via the title bar, the terminal unfocuses and I'm unable to type. I initially thought the application had frozen as I'd explicitly clicked the title bar to focus the program but my inputs weren't being reflected.

The application feels glitchy as a consequence.

This is not the behaviour in the current default terminal on pop.

**Comment by git-f0x** [comment]
This seems to be reproducible again.
