### ISSUE TITLE
Can't confirm symbol typing using spacebar

### ISSUE THREAD

**Issue by lucasjungdeveloper** [pop-os/cosmic-term#247]
When typing tilde on the terminal I normally use the spacebar to confirm it, but in the cosmic-term the only way it seems to work is when I type tilde twice

**Comment by Kartonrealista** [comment]
Are you sure this is related to the terminal, and not your chosen Input Source (Cosmic Settings -> Input Devices -> Keyboard -> Input sources)? I'm using the default Polish keyboard layout and whether it's in cosmic-term or any other place with text input I don't need to confirm ~, I just press 'Shift'  + ' ` '.

**Comment by lucasjungdeveloper** [comment]
I'm not sure about other keyboard layouts, I use the br-abnt2, but when using alacritty it works fine, so I don't think the input source is the issue

**Comment by ArjenR** [comment]
It is the same for us international with dead keys keyboard layout. I am very used to it for programming and writing. Pressing tilde and space gives you plain tilde. Pressing ~ and n gives you ñ "+o ö etc, "+space is plain "

Running latest COSMIC from repo which is regularly updated on pop os. Works everywhere except in COSMIC terminal.

**Comment by Ostheer** [comment]
I'm experiencing the same issue. Using "US, intl., with dead keys" input source, I'm expecting a space after a pending diacritic to give me the symbol standalone. Alacritty does this.

The double-press approach @lucasjungdeveloper mentions work for tildes, but not for other characters:

- <<**"**>> becomes <<**¨**>>
- <<**'**>> becomes <<**`**>>
