### ISSUE TITLE
Can't type ~ (tilda) in the terminal, but can in other places on COSMIC

### ISSUE THREAD

**Issue by msmafra** [pop-os/cosmic-term#259]
My USB keyboard has USA layout, but I use it with Brazillian portuguese. While pressing Shift + ` to get tilda inside the COSMIC Terminal it doesn't work, but works on the rest of COSMIC environment

**Comment by l-const** [comment]
In the brazilian input the ~  char is tied to ' and it is consistent across all apps. Also tried with greek and again there is not an issue. Here you can see english followed by greek and brazilian portuguese:  
![screenshot-2024-08-21-10-12-16](https://github.com/user-attachments/assets/53fa6e7c-a304-4d69-a6eb-bcb484be75fb)
It certainly not a cosmic-term issue. cc @msmafra . Could you check again?

**Comment by msmafra** [comment]
> In the brazilian input the ~ char is tied to ' and it is consistent across all apps. Also tried with greek and again there is not an issue. Here you can see english followed by greek and brazilian portuguese: ![screenshot-2024-08-21-10-12-16](https://private-user-images.githubusercontent.com/72419646/359854420-53fa6e7c-a304-4d69-a6eb-bcb484be75fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTcwMjgsIm5iZiI6MTcyNDI1NjcyOCwicGF0aCI6Ii83MjQxOTY0Ni8zNTk4NTQ0MjAtNTNmYTZlN2MtYTMwNC00ZDY5LWE2ZWItYmNiNDg0YmU3NWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE2MTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiM2U2ZDI2ZGYwOGIwMDI3ODNjZDc5MmQ4OGIyOWQ0N2QyMGViZGM1MWRiNTliNWFkNmUwYjdmNTAxOWNkODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jy1Y8p1qnB7ZgLtp2botsXcuUCU8ZyYVL5p_byXqy4w) It certainly not a cosmic-term issue. cc @msmafra . Could you check again?

Definetly was or still is a COSMIC Terminal issue, at least pre alpha 1. Any other terminal (alacritty, kitty, gnome-terminal) nor in other places inside COSMIC it happened. 

For a quick test inside Gnome not COSMIC this time, changing the layout to English Intl with dead keys on my current ABNT2 keyboards it also do not work the same way it works on the other terminals or anywhere else on the interface. At least with COSMIC Terminal inside Gnome tapping twice while holding shift appears the ~ appears.
So, using COSMIC terminal, to type ~/ I have to hold Shift and tap twice on the ` or ~ (on us layout) to do a cd ~/.

To not making it more confusing, the keyboard is an US layout plugged to my laptop that has a ABNT2 ish layout. As I use my laptop as a desktop, the keyborad is always plugged and set to English Intl for the Brazillian portuguese language which works everywhere, but COSMIC Terminal.

**Comment by msmafra** [comment]
Working now. Thank you kindly.

**Comment by MatheusPese** [comment]
For me it is not working.
Funnily enough, i installed Wayland, and it works with the combination Wayland + cosmic, but not on the default xorg.
Outside wayland, it works in every terminal but not in cosmic.
