### ISSUE TITLE
Menubar items

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-term#26]
**File**
New tab Ctrl + Shift + T
New window Ctrl + Shift + N
-separator-
Close tab Ctrl + Shift + W
-separator-
Quit Ctrl + Q

**Edit**
Copy Ctrl + Shift + C
Paste Ctrl + Shift + V
Select all Ctrl + Shift + A
-separator-
Find Ctrl + Shift + F
Advanced Find Ctrl + Shift + H (used for replace/match case/match entire word/regex)

**View**
Larger text Ctrl + =
Default text size Ctrl + 0
Smaller text Ctrl + -
-alternative spinner*-
Zoom   - 100% +
-separator-
Next tab Ctrl + Tab
Previous tab Ctrl + Shift + Tab
-separator-
Settings... Ctrl + Comma

\* "Zoom" Text benefit > shows the shortcuts. Spinner benefit > allows adjustment until done and user clicks off menu. Could keep the menu open using the text option but might be unexpected. Other ideas?

** instead of "Keyboard shortcuts..." and a separate interface in the contextmenu, we could include "Next tab" and "Previous tab" in this menu thus exposing all shortcuts.

**Comment by jackpot51** [comment]
Menu partially added in db73837. I'm working on implementing Find and then will add more items and keyboard shortcuts.

**Comment by jackpot51** [comment]
These items have all been added and they show their shortcuts. We gained some additional shortcuts that weren't designed, that I added to the View menu:

Split horizontal: Ctrl+Alt+D
Split vertical: Ctrl+Alt+R
Toggle pane maximized: Ctrl+Shift+X

We also have some that aren't in the menu:

Activate tab 0 through 8: Ctrl+Shift+1 through Ctrl+Shift+9
Focus pane directionally: Ctrl+Shift+Arrows or Ctrl+Shift+HJKL

**Comment by flukejones** [comment]
Will there be the addition of shortcuts for `alt + <num>` to select tabs directly?

**Comment by jackpot51** [comment]
Alt plus a number emits a special keycode in terminals and should not be used for key bindings.

**Comment by flukejones** [comment]
> Alt plus a number emits a special keycode in terminals and should not be used for key bindings.

I understand that, but terminals from KDE and Gnome both use this particular shortcut and it is so completely ingrained in my own muscle memory I'm having difficulty switching it off.

Do you have another suggestion for this capability? Maybe some other key combo? I could retrain to another combo maybe but whenever I want to switch tabs I default to the <key>+<num>
