### ISSUE TITLE
Can't use zellij `Alt + <⬅⬆⬇➡>` shorcuts

### ISSUE THREAD

**Issue by gaspatxo** [pop-os/cosmic-term#260]
When using [zellij](https://zellij.dev/) I can't navigate the terminal panes with `Alt + <⬅⬆⬇➡>`; instead `":3"` are inputted in the prompt.

![image](https://github.com/user-attachments/assets/5e59bcc5-d043-43c9-919f-cc3edca3513e)

This does not render zellij unusable in "cosmic-term" since zellij also allows `Alt + <hjkl>`, which does work.

**Comment by farhatizakaria** [comment]
Same issue for Bash Shell (default), I can't use ALT and CTRL with left ⬅️ and right arrow ➡️
