### ISSUE TITLE
FR: support changing the default shell

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-term#262]
I would like to use fish in cosmic-term. According to the doc, it need to be started by the terminal emulator to avoid problem: https://fishshell.com/docs/current/index.html#default-shell

**Comment by leb-kuchen** [comment]
Profiles > Make default

**Comment by wiiznokes** [comment]
> Profiles > Make default

The profiles section in files expand to nothing on my end

**Comment by leb-kuchen** [comment]
You need to create a profile like in gnome-terminal.

**Comment by wiiznokes** [comment]
@leb-kuchen are you sure this is currently implemented ? Look like gnome-terminal use dconf for this so i don't see how the two could share a compatible method https://askubuntu.com/questions/270469/how-can-i-create-a-new-profile-for-gnome-terminal-via-command-line

**Comment by wiiznokes** [comment]
Oh nevermind, i just saw the `Profils...` under it
