### ISSUE TITLE
Splits navigation shortcuts

### ISSUE THREAD

**Issue by squalou** [pop-os/cosmic-term#282]
Hi,

I didn't see doc / issue raised about that so here I go : After I split terminal, I simply can not navigate from focused split to any other.

I tried whatever usual key combination came to mind, ctrl tab, sfit tab, ctrl alt shot arrows ni any sort of combinations wit no result.

What are the shortcut *supposed* to be, to begin with ?

 Maybe I have an issue on my side,  I'm using azerty layout by the way, and experiencing some other issues with Ctrl + arrow outputting `;5C` (or A, B, D), so maybe I have something wrong elsewhere.

thank you !

**Comment by thecardinelli** [comment]
https://github.com/pop-os/cosmic-term/blob/master/src/key_bind.rs#L69
```
    bind!([Ctrl, Shift], Key::Named(Named::ArrowLeft), PaneFocusLeft);
    bind!([Ctrl, Shift], Key::Character("H".into()), PaneFocusLeft);
    bind!([Ctrl, Shift], Key::Named(Named::ArrowDown), PaneFocusDown);
    bind!([Ctrl, Shift], Key::Character("J".into()), PaneFocusDown);
    bind!([Ctrl, Shift], Key::Named(Named::ArrowUp), PaneFocusUp);
    bind!([Ctrl, Shift], Key::Character("K".into()), PaneFocusUp);
    bind!([Ctrl, Shift], Key::Named(Named::ArrowRight), PaneFocusRight);
    bind!([Ctrl, Shift], Key::Character("L".into()), PaneFocusRight);
```
