### ISSUE TITLE
[Bug] Resetting text size (Ctrl+0) while already at default text size crashes terminal

### ISSUE THREAD

**Issue by drazil100** [pop-os/cosmic-term#291]
If you use Ctrl+0 without changing the text size, or after changing it and then changing it back to normal text size crashes the terminal window.

**Comment by MoSal** [comment]
FWIW, I can't reproduce this.

Run the terminal from another terminal, and see if it panics or segfaults. If it panics, post the panic info printed. If it segfaults, try to get a backtrace with gdb/lldb.

**Comment by drazil100** [comment]
```
austin@vivobook:~$ thread 'main' panicked at src/terminal_box.rs:366:58:
IndexSet: index out of bounds
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Anything else I can provide?

**Comment by drazil100** [comment]
Also here is the version I have if that matters:

`Version: 0.1.0~1723732679~24.04~72ffa01`

Running this in the pop 24.04 alpha

**Comment by MoSal** [comment]
> ```
> austin@vivobook:~$ thread 'main' panicked at src/terminal_box.rs:366:58:
> ```

That's useful.

Can you compile and test, first without any changes, and if the panic is still triggered, can you test with this commit https://github.com/pop-os/cosmic-term/commit/7c5d5440e5a560238de3666d7ead6970477a7dd6 reverted?

**Comment by drazil100** [comment]
Sure I can do that at some point. Might be a bit cause I'm traveling but I'll see what I can do in the car.

**Comment by drazil100** [comment]
Ok I thought I knew what I was doing but how do I compile this? Readme doesn't include build instructions.

**Comment by MoSal** [comment]
@drazil100 

I will provide you with a couple of binaries if that's more convenient:

Download the artifacts at the bottom of [this page](https://github.com/MoSal/cosmic-term/actions/runs/10421563086) and [this page](https://github.com/MoSal/cosmic-term/actions/runs/10421432173).

Extract the binaries, give them executable permissions, and run them, e.g.

The first one:
```
7z x cosmic-term-x86_64-5f28889.zip
chmod +x cosmic-term-x86_64-5f28889
./cosmic-term-x86_64-5f28889
```

The second one:
```
7z x cosmic-term-x86_64-bfe9e91.zip
chmod +x cosmic-term-x86_64-bfe9e91
./cosmic-term-x86_64-bfe9e91
```

* The first one should behave identically to your installed version.
* The second one contains what I think should be a proper fix for the issue, although as I stated earlier, I can't actually reproduce it in my (non-COSMIC) setup.

(The binaries are compiled with GitHub runners. So you don't have to trust me to run them.)

For future reference, you can compile and run cosmic-term yourself with these trivial steps:

```
git clone https://github.com/pop-os/cosmic-term
cd cosmic-term
# make sure cargo is installed via your distro package manager or rustup
cargo build --release
# running the built binary
./target/release/cosmic-term
```

**Comment by drazil100** [comment]
I figured it out just before I lost internet. Installed the dependencies listed on cosmic-epoch and figured out I could usee just -l and built with build-release. 

Anyway the first one you wanted me to try (no changes) panicked just like before. reverting https://github.com/pop-os/cosmic-term/commit/7c5d5440e5a560238de3666d7ead6970477a7dd6 fixed it. No more panic.

**Comment by MoSal** [comment]
@drazil100

Cool.

Can you reset and try with [this commit](https://github.com/pop-os/cosmic-term/commit/9bbaf31c447330a9c03b5b34edcf83b3ae6fbf8c.patch) applied? Or alternatively, try the second binary mentioned above.

Something like this should work:

```
# make sure you have no important files in the cosmic-term folder
git reset --hard origin/master
curl -LO https://github.com/pop-os/cosmic-term/commit/9bbaf31c447330a9c03b5b34edcf83b3ae6fbf8c.patch
git am 9bbaf31c447330a9c03b5b34edcf83b3ae6fbf8c.patch
cargo build --release
```

**Comment by drazil100** [comment]
Works! 

Thank you for giving me something to do on this long roadtrip xD Also while I am very familiar with git for personal projects I have never had to apply a patch like that so thank you for the experience.

If you need anything else let me know!

Btw probably unrelated but with both the revert and the patch I would occasionally get this when pressing Ctrl+0
```
[2024-08-16T16:19:35Z WARN  calloop::loop_logic] [calloop] Received an event for non-existence source: TokenInner { id: 3, version: 25, sub_id: 0 }
```

**Comment by MoSal** [comment]
@drazil100 

Thank you for taking the time to test. A PR with the supposed fix was submitted.
