### ISSUE TITLE
ctrl click to follow url

### ISSUE THREAD

**Issue by codegod100** [pop-os/cosmic-term#296]
would be a nice feature

**Comment by A-Walrus** [comment]
Another related thing is OSC8, which allows links with display text and url.

Running `printf '\033]8;;http://example.com\033\\This is a link\033]8;;\033\\n'` in supporting terminals will show this is a link, and when it's clicked take you to `example.com`.


Adoption: https://github.com/Alhadis/OSC8-Adoption/

**Comment by ahoneybun** [comment]
This is very handy to have for signing into services such as Tailscale that give you a URL to sign in though.

**Comment by WatchMkr** [comment]
We're tracking this here https://github.com/pop-os/cosmic-term/issues/10

**Comment by codegod100** [comment]
closing as dupe
