### ISSUE TITLE
Helix-editor rendered incorectly

### ISSUE THREAD

**Issue by KoreshKrasa** [pop-os/cosmic-term#297]
helix-editor has rendering issues in cosmic-term
Comparison with alacritty (on the right). Main issue "bar" cursor rendered as block and symbol hides character.
alacritty 0.13.2
![screenshot-2024-08-18-10-56-06](https://github.com/user-attachments/assets/883823e0-a948-4d03-920e-34edef1adfea)
![screenshot-2024-08-18-10-56-28](https://github.com/user-attachments/assets/69ecd4dc-5465-4589-ab8c-9c9152232191)

**Comment by A-Walrus** [comment]
Solved by #306

**Comment by eduardz1** [comment]
> helix-editor has rendering issues in cosmic-term Comparison with alacritty (on the right). Main issue "bar" cursor rendered as block and symbol hides character. alacritty 0.13.2 ![screenshot-2024-08-18-10-56-06](https://github.com/user-attachments/assets/883823e0-a948-4d03-920e-34edef1adfea) ![screenshot-2024-08-18-10-56-28](https://github.com/user-attachments/assets/69ecd4dc-5465-4589-ab8c-9c9152232191)

In these screenshots it's also visible another problem that has been bugging me for a while, full screen apps such as helix are rendered with a border on the bottom and on the right. Is there an issue tracking this? Can it be fixed?
