### ISSUE TITLE
[Feature Request]: Change terminal tabs with Ctrl/Alt + Number (1-9)

### ISSUE THREAD

**Issue by bittin** [pop-os/cosmic-term#299]
Hey!

It would be nice to be able to change terminal tabs with Ctrl or Alt and a number key on the keyboard, as i am used to doing this to change between open terminal tabs instead of having to click with the mouse while working at the keyboard

**Comment by bittin** [comment]
my partner @lemonzest79 talked about Ctrl + Tab might work for newer terminals, and that worked, but i am used to the older way of using Ctrl or Alt and numbers, to change between tabs, but i guess this is better then nothing and that maybe i have to relearn to use the newer modern way

**Comment by Fingel** [comment]
You can change tabs by number using Ctrl+Shift+#
