### ISSUE TITLE
panic in wgpu 0.18.0 when AMDVLK 2023.Q4.3 on Radeon RX 7900 XTX

### ISSUE THREAD

**Issue by jokeyrhyme** [pop-os/cosmic-term#30]
- this version/commit of cosmic-term: https://github.com/pop-os/cosmic-term/tree/d9c2ab72eb8c6fe36365cbe19a4d9c033b9d4555
- which uses this version/commit of libcosmic: https://github.com/pop-os/libcosmic/tree/1bd39b17ae7c97934ea214028cd31c578b589e3e
- which uses wgpu 0.18
- on Arch Linux with this version of AMDVLK: https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2023.Q4.3
- AMDVLK is the default, so this bug causes `cosmic-term` to be unable to be launched from anywhere where environment variables are unable to be customised (e.g. `cosmic-launcher`, `cosmic-app-library`, etc)

launching `cosmic-term` or `AMD_VULKAN_ICD=AMDVLK cosmic-term` results in the following error:

```
wl_drm@53: error 1: Format not advertised by wl_drm
warning: queue 0x563961aec090 destroyed while proxies still attached:
[2024-01-07T20:34:57Z ERROR wgpu_hal::vulkan::adapter] get_physical_device_surface_capabilities: An unknown error has occurred, due to an implementation or application bug
thread 'main' panicked at $HOME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.18.0/src/backend/direct.rs:778:18:
Error in Surface::configure: Validation Error
Caused by:
Surface does not support the adapter's queue family
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

all of these do work, however:

- launching `AMD_VULKAN_ICD=RADV cosmic-term` works just fine
- ensuring this environment variable is set early enough to apply to `cosmic-launcher`, etc
- completely uninstalling AMDVLK so that RADV is the only Vulkan implementation

I do not expect this to be addressed in wgpu nor `cosmic-term` (but awareness may be handy later)

**Comment by Drakulix** [comment]
Is there an open wgpu issue for this?

**Comment by jokeyrhyme** [comment]
Not yet, I'll raise one when I'm back at a computer

**Comment by jokeyrhyme** [comment]
Reported: https://github.com/gfx-rs/wgpu/issues/5021

**Comment by jokeyrhyme** [comment]
After being prompted over there, I tested in X11 and other compositors...

I could not reproduce this panic in `sway`, GNOME wayland, or GNOME x11, so it's likely specific to `cosmic-comp`

I'd previously encountered an earlier bug in AMDVLK that was breaking wgpu so I incorrectly assumed it was another similar occurrence

**Comment by ids1024** [comment]
So with AMDVLK, this wouldn't be using Mesa's EGL/Vulkan WSI code, and instead would use AMD's own implementation? Looking at https://github.com/GPUOpen-Drivers/pal/blob/dev/src/core/os/amdgpu/wayland/waylandWindowSystem.cpp, it seems to require `wl_drm`. (While other drivers have moved to the newer dmabuf protocol.) 

So it may be a bug with cosmic-comp's `wl_drm` implementation.

Logs from running the client with `WAYLAND_DEBUG=1` may provide some more information here.

**Comment by ids1024** [comment]
So the client is trying to use `875713112`. That's `XRGB8888`. Which I think should be supported fine?

But `wl_drm::format` isn't being sent here, so either the compositor isn't advertising any formats, or the client isn't waiting for the compositor before selecting the format.

**Comment by ids1024** [comment]
Yeah, I think `wl_drm::format` should appear in the log right after `wl_drm::capabilities`. Is the format list empty, or did `wl_drm::Format::try_from(*format as u32)` fail to convert any formats, somehow?

**Comment by jokeyrhyme** [comment]
I can add more instrumentation somewhere and recompile to find out?

**Comment by ids1024** [comment]
I'd probably change https://github.com/pop-os/cosmic-comp/blob/f75d89b4240fb25f6e43443efd18f95c8484a620/src/wayland/protocols/drm.rs#L93-L98 to something like:

```rust
for format in global_data.formats.iter() {
    dbg!(format);
    if let Ok(converted) = dbg!(wl_drm::Format::try_from(*format as u32)) {
        drm_instance.format(converted as u32);
    }
}
```

I'm not really familiar with AMDVLK, but I should be able to test it, assuming it works with any modern integrated AMD GPU.

**Comment by jokeyrhyme** [comment]
Hmmm, I've tried compiling `cosmic-comp` with `cargo build --release` and `cargo build` (debug) and neither results in `dbg!(...)` output ending up in `journalctl -xb`

I even put a trivial `dbg!("cosmic-comp starting up");` in main.rs to confirm, and it doesn't appear in the logs

Do I need to run `cosmic-comp` or `cosmic-session` with an environment variable to get this log output?

**Comment by ids1024** [comment]
Oh yeah. `dbg!` will just be written to stderr, not journald. Something like `./target/release/cosmic-comp 2>&1 | tee log-file` is what I often use to test that sort of thing. Something like `tracing::error!` will instead write to both journald and stderr.

**Comment by jokeyrhyme** [comment]
Okay, I instrumented the start of cosmic-comp::main() and cosmic-comp::wayland::protocols::drm::WlDrmState::bind() , as well as the body of the `for` loop in the latter

I can see that `bind()` is called multiple times when trying to run `cosmic-term`, but there is no output from inside the loop, so I assume this means `global_data.formats` is empty

**Comment by ids1024** [comment]
Seems AMDVLK recently dropped support for older graphics, including the Renoir APU I have handy, but https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2023.Q3.3 works.

I am able to reproduce the issue easily with that.

**Comment by ids1024** [comment]
Ah, so `.filter(|f| f.modifier == Modifier::Invalid)` ends up filtering out all of the formats. ("Invalid" here means formats that work with an "implicit dmabuf modifier".)

Removing that gives me `wl_drm@53: error 2: buffer import failed` instead. Presumably Mesa's EGL failed  to import the dmabuf.

I could make sense that Mesa is requiring explicit modifiers for import while AMDVLK needs `wl_drm` which doesn't support them, but then if other compositors work with the same drivers, I'm not sure what they're doing differently.

**Comment by ids1024** [comment]
https://github.com/Smithay/smithay/pull/1274 seems to fix this.

**Comment by i509VCB** [comment]
Also an issue to see if amdvlk will implement zwp-linux-dmabuf-v1: https://github.com/GPUOpen-Drivers/pal/issues/96

**Comment by ids1024** [comment]
Yeah, AMDVLK should move to the dmabuf protocol, and probably make use of explicit modifiers. `wl_drm` is basically a deprecated API at this point, and Mesa and compositors are interested in dropping support for it once it's no longer needed anywhere.

RADV likely offers overall better Wayland support, though there is still more to improve in Mesa's Vulkan and EGL Wayland WSI support.

**Comment by ids1024** [comment]
This should be fixed now that the Smithay PR is merged, and cosmic-comp has updated Smithay.

**Comment by jokeyrhyme** [comment]
I can confirm that this is fixed for me: https://github.com/pop-os/cosmic-epoch/pull/186
