### ISSUE TITLE
Cannot input `~` or other dead keys in cosmic-term (Swedish keyboard)

### ISSUE THREAD

**Issue by VorpalBlade** [pop-os/cosmic-term#318]
I use Swedish keyboard layout. Typing `~` requires `AltGr+(a key next to enter)` followed by `space`. This is because `~` is a dead key used to type ẽ etc as well. Also typing a backquote (as used for code style in markdown) is a dead key. It also doesn't work.

This doesn't work in cosmic-term, but does in the cosmic text editor. It seems to affect all dead keys (regardless if they are on AltGr or not). Other non-dead keys on AltGr such as $ work fine.

* Version is 1.0.0.alpha.1-2 installed with pacman on Arch Linux.
* System is using Intel graphics (on an i7-8550U)

**Comment by Elias-Graf** [comment]
Might be related: https://github.com/pop-os/cosmic-term/issues/259.

**Comment by ascense** [comment]
As far as I can tell, this looks to be a specific issue with the handling of the Space-key. The key event gets captured here: https://github.com/pop-os/cosmic-term/blob/a71f0dcdf9e1cc8797a27f641cac5f1c0a667e84/src/terminal_box.rs#L780 instead of the proper processing here (where proper composing would take place): https://github.com/pop-os/cosmic-term/blob/a71f0dcdf9e1cc8797a27f641cac5f1c0a667e84/src/terminal_box.rs#L806

**Comment by ascense** [comment]
This quick-and-dirty fix resolves it for me, but I don't think this is the best way to handle it: https://github.com/ascense/cosmic-term/commit/01818f84e86148ac51c096fa5664e02e6ca3cc6b

**Comment by eduardz1** [comment]
> This quick-and-dirty fix resolves it for me, but I don't think this is the best way to handle it: [ascense@01818f8](https://github.com/ascense/cosmic-term/commit/01818f84e86148ac51c096fa5664e02e6ca3cc6b)

This looks like the cleanest way of implementing it, even on the latest commit it's just:

```diff
diff --git a/src/terminal_box.rs b/src/terminal_box.rs
index 495de7d..db1933b 100644
--- a/src/terminal_box.rs
+++ b/src/terminal_box.rs
@@ -655,6 +655,7 @@ where
             Event::Keyboard(KeyEvent::KeyPressed {
                 key: Key::Named(named),
                 modifiers,
+                text,
                 ..
             }) if state.is_focused => {
                 for key_bind in self.key_binds.keys() {
@@ -778,11 +779,15 @@ where
                         status = Status::Captured;
                     }
                     Named::Space => {
+                        // Keep this instead of hardcoding the space to allow for dead keys
+                        let character = text.and_then(|c| c.chars().next()).unwrap_or_default();
+
                         if modifiers.control() {
                             // Send NUL character (\x00) for Ctrl + Space
                             terminal.input_scroll(b"\x00".to_vec());
                         } else {
-                            terminal.input_scroll(format!("{}{}", alt_prefix, " ").into_bytes());
+                            terminal
+                                .input_scroll(format!("{}{}", alt_prefix, character).into_bytes());
                         }
                         status = Status::Captured;
                     }
```
