### ISSUE TITLE
Cannot scroll inside of the micro text editor

### ISSUE THREAD

**Issue by Daktyl198** [pop-os/cosmic-term#340]
When using the micro text editor (https://github.com/zyedidia/micro/), I find that I cannot scroll when using cosmic-term. As this is my default text editor, it prevents me from using Cosmic Term as my default terminal. I am unfortunately not well versed in exactly which mouse events it reads.

Addition: I can't change the title, but I can't scroll within btop either, which implies it's a general lack of a feature for the terminal.

**Comment by Tommimon** [comment]
Also other key combinations don't work in micro, such as `Shift + End` or `Shift + Ctrl + Right`.
But `Shift + Right` works.

Same for `Home` and `Left` counterparts.

**Comment by msmafra** [comment]
I'm having the same problems. No begin or end of lines, no full line selection etc. Works when I'm on alacritty, kitty, console etc.
Inside Nano, it works.

**Comment by msmafra** [comment]
Even with commit 353bbbe Shift + End, Shift + Home still not working.
End, Home, Shift + Up, Down, Left or right are working.

> Also other key combinations don't work in micro, such as `Shift + End` or `Shift + Ctrl + Right`. But `Shift + Right` works.
> 
> Same for `Home` and `Left` counterparts.

Even with commit 353bbbe Shift + End, Shift + Home still not working for me.
End, Home, Shift + Up, Down, Left or right are working.
