### ISSUE TITLE
Cosmic term takes a long time to appear in Alt + Tab menu in GNOME

### ISSUE THREAD

**Issue by msehnout** [pop-os/cosmic-term#359]
Hello,

I tried cosmic term on my Fedora 40 with GNOME Shell 46 and noticed it takes a very long time to appear in the Alt+Tab menu. I'm not sure this is necessarily Cosmic term issue, but so far I have seen this issue only with KeePassXC.  All other apps work fine.

https://github.com/user-attachments/assets/4ef201f0-2569-4a11-aa7b-73ccb5cbab23

**Comment by mmstick** [comment]
You should report this issue to GNOME, since it shouldn't be doing that either way.

**Comment by msehnout** [comment]
Sure, I can report the issue to GNOME. Can you please help me understand what you meant by `it shouldn't be doing that either way`? I suppose it should display the app in the Alt Tab menu, shouldn't it?

**Comment by msehnout** [comment]
Gnome devs also say it is not their issue. Closing as this as stuck in a dead end.

**Comment by MoSal** [comment]
@msehnout 

If you can test using GNOME+X11, that should at least provide you with an additional data point.

**Comment by msehnout** [comment]
I don't know how to run cosmic term with X11, but I tried setting `StartupNotify=false` in the desktop file. It helped with the issue for KeePassXC, but didn't help in case of cosmic term so I just removed it from my system....

**Comment by MoSal** [comment]
I meant running GNOME itself in X11 mode (supposedly possible in Fedora 40, but not 41), but whatever..
