### ISSUE TITLE
Applications like btop do not render correctly in COSMIC-term

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-term#398]
Certain applications like btop appear to render incorrectly in COSMIC term, this appears to be related to the handling of the braille characters in COSMIC term as disabling them in btop fixes the problem.

[wierd-render.webm](https://github.com/user-attachments/assets/cf1afeb7-b6c2-4f15-8d95-eae5735669f7)

To disable the braille characters in btop press m, press on the options, use the arrow keys to navigate down to graph symbol and change with the arrow keys.

**Comment by git-f0x** [comment]
Same issue as #66, #166, #275, and pop-os/cosmic-text#237.

**Comment by leviport** [comment]
Tracking in https://github.com/pop-os/cosmic-text/issues/237
