### ISSUE TITLE
Bash shortcuts are missing

### ISSUE THREAD

**Issue by SUPERCILEX** [pop-os/cosmic-term#40]
Specifically, I need Alt+Backspace: https://help.gnome.org/users/gnome-terminal/stable/adv-keyboard-shortcuts.html.en#bash-shortcuts

**Comment by SUPERCILEX** [comment]
Just saw the blog post BTW, and damn is it fast on a 1GB file—congrats!

**Comment by jackpot51** [comment]
Can you get what is printed in gnome-terminal if you press Ctrl+V and then Alt+Backspace? I'm using vi mode for bash so I don't see the control characters.

**Comment by SUPERCILEX** [comment]
> Can you get what is printed in gnome-terminal if you press Ctrl+V and then Alt+Backspace?

Nothing is printed, not sure what this is supposed to do.

This is maybe helpful:
```
> showkey -a

Press any keys - Ctrl-D will terminate this program

^[^? 	 27 0033 0x1b
 	127 0177 0x7f
```

**Comment by jackpot51** [comment]
That is helpful, thanks!
