### ISSUE TITLE
Change title of tab/window to currently running command

### ISSUE THREAD

**Issue by SUPERCILEX** [pop-os/cosmic-term#41]
It'd be nice to have the title of the currently running command be shown in the tab title and transitivity for the currently shown tab to have its title in the window.

Probs should only be a thing for commands that take longer than 1 second? Maybe 3?

**Comment by SUPERCILEX** [comment]
> Probs should only be a thing for commands that take longer than 1 second? Maybe 3?

Actually, I take this back. Just do it always and call it a feature. The title will always show the name of the last executed command.

**Comment by jackpot51** [comment]
This would be very difficult to implement.

**Comment by SUPERCILEX** [comment]
Ok, so apparently this is something shell should do: https://github.com/nushell/nushell/issues/2527#issuecomment-1880155982

So makes sense, thanks.

**Comment by atiq-cs** [comment]
yep, gnome's default ptyxis also does that (changes title to running cmd)
