### ISSUE TITLE
Terminal does nothing on COSMIC & Pop w/ Wayland on NVIDIA RTX 3070Ti Mobile

### ISSUE THREAD

**Issue by ZVNexus** [pop-os/cosmic-term#47]
For example, when I type some characters, it doesn't actually render them until I click on the terminal window.

AMD Ryzen 9 6900HX
NVIDIA RTX 3070Ti Mobile

This is the behavior when I select "integrated" GPU, however when I select "Hybrid" the terminal refuses to do anything, even with mouse clicks.

**Comment by ZVNexus** [comment]
Adding some additional context, when running under the original PopOS shell with X11, the app does not crash and I can use it fine.

I tried Pop on Wayland, and it does crash. Wayland specific NVIDIA issues?

**Comment by MoSal** [comment]
If pressing `Esc` twice fixes the issue. Then I think it's a (known) regression from 928269a2394b6b6a74b2fcca89b4ef17ed672020.

**Comment by ZVNexus** [comment]
@MoSal Looks like that was it, for integrated graphics. There's still some weird issues going on with hybrid graphics for NVIDIA laptops.

**Comment by ZVNexus** [comment]
The app just sits here on hybrid graphics, and cannot interact with the app.

COSMIC: Sits here, does nothing.
Pop on Wayland: App works for .2 seconds, then crashes
Pop on X11: Works fine
![image](https://github.com/pop-os/cosmic-term/assets/19439046/fea2433c-b68e-4620-9369-2f83a50fa964)

**Comment by jackpot51** [comment]
If you can build from source, try to run the terminal with:

```
cargo run --release --no-default-features
```

This will disable WGPU that may be causing this issue.

**Comment by ZVNexus** [comment]
@jackpot51 I did so, and can confirm it works perfectly fine now.

**Comment by jackpot51** [comment]
That is possible. We have some updates to this only in the `master` staging repository.

**Comment by jackpot51** [comment]
Check `apt-cache policy cosmic-term`:

The release version is `0.1.0~1704845884~22.04~4ec3e5b`
The staging version is `0.1.0~1705081333~22.04~c5c78b0`, which is newer and up to date

We will release updates soon.

**Comment by jackpot51** [comment]
https://github.com/pop-os/repo-release/pull/310

**Comment by ZVNexus** [comment]
@jackpot51 I can confirm that after updating my packages, the issue went away. Not sure what commit fixed it but all good now thanks!
