### ISSUE TITLE
New instances sometimes launch with multiple tabs

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-term#50]
When launching a new instance of Cosmic-Term in either Gnome or Cosmic in Pop!_OS, the application launches with two tabs open. 

One tab is titled "New Terminal" and the other takes the format of "`user`@`hostname`:~". 

This is true if launches from the launcher, using the `super + t` shortcut, from the application view, from the dock, or from a terminal.

When I close the "`user`@`hostname`:~" tab, the application remains open, and switches to the "New Terminal" tab - which is entirely non-responsive, so far as I can tell.

**Comment by jackpot51** [comment]
Please test with master staging, this should be fixed by #37

**Comment by XV-02** [comment]
Looks like this was remedied before I opened it! #37 successfully addresses this.

**Comment by XV-02** [comment]
I'm going to reopen this issue, and tweak the title a little. 

While I don't see cosmic-term opening with multiple tabs every time, I am seeing it infrequently. 

More over, I can semi-reliably make it happen about once in ten times while I am aggressively spamming the `super + t` shortcut to launch terminals in a Cosmic DE session.

**Comment by snaggen** [comment]
This should be fixed by https://github.com/pop-os/cosmic-term/commit/4401a7dbef3e1579af9694c5f6c38c1b788a86e2
