### ISSUE TITLE
cosmic-term cut/paste doesn't work

### ISSUE THREAD

**Issue by gantryyork** [pop-os/cosmic-term#55]
While trying to cut/paste an error message from cosmic-term into my browser (Brave),

1. highlight, middle button doesn't work
2. edit > cut, right-click > paste doesn't work
3. cntr-c, cntr-v, doesn't work

I also tried all the above into another app (Joplin), doesn't work

**Comment by gantryyork** [comment]
After update, cut/past works  with the following

- [ ] highlight copy, middle button paste
- [ x] edit > copy, right-click > paste
- [ x] ctrl-c copy, ctrl-v paste

**Comment by WatchMkr** [comment]
Closing this one to track middle click paste here: https://github.com/pop-os/cosmic-term/issues/49
