### ISSUE TITLE
Cosmic-Term does not render reliably on some hardware.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-term#6]
When unfocused, Cosmic-Term renders as a garbled mess ~~in tiling mode~~ in Cosmic. ~~; I haven't tested in Gnome!Pop yet.~~

This seems to only be true when no other active element (Mouse cursor, floating window, etc.) overlaps with the Cosmic-Term window. I cannot capture this with Cosmic-Screenshot. 

Screenshots will show: 
![Screenshot_2023-12-22_14-01-48](https://github.com/pop-os/cosmic-term/assets/98765732/72bcf6ef-6bec-41f9-b35f-9a4380392fc7)

When the User sees:
![IMG20231222140411](https://github.com/pop-os/cosmic-term/assets/98765732/b55d44b2-8c7b-4d70-82e8-70f2c21bc30d)

This behaviour is consistent whether or not the terminal is changing state (for example, running a command like `apt update` which prints to stdout), and does not appear to be tied to screen resolution or other display-specific issues. 

Edit 1: This is not an issue for Cosmic-Term on Gnome!Pop.
Edit 2: Strike through on "in tiling mode" to reflect also seeing it in floating mode.

**Comment by mmstick** [comment]
This is probably a graphics driver issue. It renders fine on my AMD system with tiling enabled in COSMIC.

**Comment by XV-02** [comment]
Potentially. The system uses Intel HD 4000 graphics. It probably isn't exclusively a driver issue though, as it seems fine in both Xorg and Wayland Gnome.

**Comment by XV-02** [comment]
On the same hardware, I'm also seeing the same behaviour when floating the terminal window without focus or any other over-lapping, active elements (cursors, other windows, etc.)

I've updated the issue title to reflect this.

**Comment by ryanabx** [comment]
To clarify, have you tried cosmic-term on GNOME or KDE to verify? Might help narrow the issue down (either compositor issue, or cosmic-term specific issue, regardless of DE)

**Comment by XV-02** [comment]
So, Cosmic-Term was tried on both Cosmic itself, in both Tiling and Floating workspace mode, and with the window itself both Tiled and Floated. In all possible combinations, the window was rendered incorrectly when unfocused and without any other overlapping windows or UI elements. 

I then tried it in Gnome with our extensions enabled - all on the same hardware - and using both Xorg and Wayland, in both Tiling and Floating DE modes, and with the window both tiled and floated in Tiling mode. On Gnome, the rendering issue never presented.

I think mmstick is broadly right about this being in someway a graphics driver issue, as I can cause it to happen on external displays with that same hardware, and cannot cause it to happen on an array of newer hardware. However, this means that it is a demonstrable regression over our currently shipped Gnome experience. It also means that, on the compositor/DE side, Gnome is supporting HD 4000 graphics successfully, while we aren't fully achieving that.

**Comment by XV-02** [comment]
I've changed the title to reflect that this seems somewhat hardware specific. I'll need to find older hardware in the lab to poke at, and see if there is a rough cut off for which generation of graphics this seems to slip up on.

**Comment by ids1024** [comment]
So HD 4000 is Ivy Bridge? I don't remember which Intel generation is the oldest with Vulkan support, but that's fairly early for it, so if it's supported I'm not surprised that it might be buggy.

Does it work with `WGPU_BACKEND=gl`?

**Comment by XV-02** [comment]
This looks to have been resolved. I'm uncertain at what point, though, but am no longer seeing this issue.
