### ISSUE TITLE
Can't tell overlapping windows apart due to lack of border/shadow

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-term#63]
When using multiple non-tiled COSMIC Terminal windows, due to the lack of border or shadow around the windows, the background colors blend together and it's very difficult to tell where the resize handle is and where the clickable portion to switch to the other window is.

![image](https://github.com/pop-os/cosmic-term/assets/7199422/be3d3297-c364-41a5-8cd1-36677c02a679)

This issue is present in both GNOME and COSMIC Epoch. It's mitigated by the active hint, but most other apps don't rely on that.

**Comment by WatchMkr** [comment]
Border and shadow to be added in libcosmic. There's an issue on that repo.
