### ISSUE TITLE
Must re-press CTRL modifier to be able to close last tab

### ISSUE THREAD

**Issue by snaggen** [pop-os/cosmic-term#67]
If you open a terminal and open 3 tabs. then just close all tabs by holding ctrl down (and keeping it down the whole time) and press d multiple times. Then when the tab bar goes away, the key presses doesn't take any more so the last terminal will not exit as expected. 
If you lift ctrl and press ctrl-d, the window is closed. 

I have tested to modify the view function, to always show the tab bar 
```rust
            if tab_model.iter().count() >= 1 {
```
With that modification things work as expected, so it is something around the rendering/non-rendering of the tab bar.

**Comment by ChocolateLoverRaj** [comment]
I tried it today and I was able to close multiple tabs by holding down Ctrl and pressing D multiple times without releasing the Ctrl key. It also works by just holding down both Ctrl and D.

**Comment by WatchMkr** [comment]
This appears to be fixed.
