### ISSUE TITLE
Unusual prompt rendering after horizontal resize

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-term#71]
Wasn't sure how to title this. The issue is shown below:

[cosmic-term.webm](https://github.com/pop-os/cosmic-term/assets/150025636/5ef9647d-15a5-42b8-b1c8-76ab8ce6110a)

Captured on GNOME since COSMIC doesn't yet have screen recording, but the issue is the same in either.
The prompt becomes weird when the window is shrunk too much horizontally and `cosmic-term` closes if it's shrunk even further.

**Comment by WatchMkr** [comment]
Apps are designed for a 360px minimum width. We'll want to start setting that.

**Comment by git-f0x** [comment]
I'll close this since the fix is part of the MVP Issue List.
