### ISSUE TITLE
Settings organization and names

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-term#96]
All setting names are sentence case.

**Appearance**
- Theme
- Color scheme dark
- Color scheme light
- Zoom steps
- Background opacity (slider)

**Font**
- Font
- Font size
- Advanced font settings (List item accordion widget)
  - Font stretch
  - Normal font weight
  - Dim font weight
  - Bold font weight
  - Make bold text brighter

**Splits**
- Split style
  - subtext “Single split adapts to window width changes”
  - Segmented Control widget
  - Single-split | Multi-split
  - Default Single-split
- Typing focus follows mouse
  - Default off
- Show active split hint
  - Default on

**Advanced**
- Show header
  - subtext “Reveal the header from the right-click menu.”

**Comment by jackpot51** [comment]
I've done most of this re-org with the settings we already have. We are still missing many of the split options, and we are missing the list accordion.

**Comment by jackpot51** [comment]
This is implemented except for the splits change, which I will instead track in #97
