### ISSUE TITLE
Context menu for MVP

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-term#98]
- Copy  Ctrl + Shift + C
- Paste Ctrl + Shift + V
- Select All Ctrl + Shift + A
- Split Ctrl + ;
- Toggle split maximize Ctrl + Shift + M
- New tab Ctrl + Shift + M
- Settings Ctrl + ,
- Show header (on/off toggle)

**Comment by jackpot51** [comment]
This is implemented except for the splits change, which I will instead track in #97
