### ISSUE TITLE
Profiles feature

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-term#99]
**Profiles**
- Files > Profiles…
  - Opens ContextDrawer to create and edit profiles
- Files > Active profile > List of profile names with short cuts
  - Assign Ctrl+Shift+Num to profiles

**Profiles ContextDrawer**

![screenshot-2024-01-31-04-34-43](https://github.com/pop-os/cosmic-term/assets/3430283/0e6281df-5cd6-498f-b96f-da182fcd5b91)

![screenshot-2024-01-31-04-34-58](https://github.com/pop-os/cosmic-term/assets/3430283/ef5c45c1-1740-4208-9362-130e3cf72e9e)

![screenshot-2024-01-31-04-35-20](https://github.com/pop-os/cosmic-term/assets/3430283/4fd6096c-452d-4795-b97b-39a33aa205a6)

**Comment by jackpot51** [comment]
This was mostly inplemented in #131. I will come back tomorrow to complete it

**Comment by jackpot51** [comment]
As discussed with @maria-komarova, we can drop custom font in profiles for the MVP. It is complicated to implement. All other features should be implemented.

**Comment by atiq-cs** [comment]
command line for this i.e., `--profile` is not implement yet, right?
